sudo: required
dist: trusty

language: node_js
node_js:
  - "node"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fonttools fontforge

install:
  - npm install

script:
  - make
